
%clearing variables & screen
clear

%frequency
fs = 8000;

%durations
w = 1;
h = 0.5;
q = 0.25;
res = 0.01;

%notes
G = 220*2^(-2/12) * 2;
A = 220 * 2;
B = 220 * 2^(2/12) *2;
D = 220 * 2^(5/12) * 2;

%duration array
l = [q q q q ...
     q q h ...
     q q h ...
     q q h ...
     q q q q ...
     q q q q ...
     q q q q ...
     w ...
     q q q q ...
     q q h ...
     q q h ...
     q q h ...
      q q q q ...
      q q q q ...
      q q q q ...
      h+q q ...
      q q q q ...
      q q h ...
      q q h ...
      q q q q ...
      q q q q ...
      q q q q ...
      q q q q ...
      h+q q ...
      q q q q ...
      q q h ...
      q q h ...
      q q q q ...
      q q q q ...
      q q q q ...
      q q q q ...
      w];
  
  %notes array
  notes = [B A G A ...
           B B B ...
           A A A ...
           B D D ...
           B A G A ...
           B B B B ...
           A A B A ...
           G ...
           B A G A ...
           B B B ...
           A A A ...
           B D D ...
           B A G A ...
           B B B B ...
           A A B A ...
           G D ...
           B A G A ...
           B B B ...
           A A A ...
           B D D D...
           B A G A ...
           B B B B ...
           A A B A ...
           G D ...
           B A G A ...
           B B B ...
           A A A ...
           B D D D ...
           B A G A ...
           B B B B ...
           A A B A ...
           G];
 y=[];
 %y2=[];
 %sf = [];
tnotes = [p p p p p];
tdur = [h h w q h];
 for i = 1:size(l,2)
     

         
     t1 = 0:(1/fs):(l(i)-l(i)/fs);
    if i==1
         g = cos(2*pi*notes(i)*t1);
         t = t1;
         g = g/max(g(:))
    end
        tn = t1/max(t1(:))
        
     y = [y,exp(-x).*cos(2*pi*notes(i)*t1)];

     %y2 = [y2,t1*0];
     %sf = [sf,y,y2];
 end
 y=y/max(y(:));
 plot(t,g)
 sound(y,fs)
